### ISSUE TITLE
Available Midori128 implementation in C or C++? 

### ISSUE THREAD

**Issue by omarfayez95** [tomirio619/Midori#1]
Hey! 

I am a masters student in Business Informatics, and I have a project where I evaluate different Information Security protocols on the Arduino Uno R3, Midori being one of them. I currently have Midori64 implemented, however my Midori128's encryption is completely wrong, and I'm having trouble fixing it. The issue is due to the Sbox permutations (I debugged following your very helpful Intermediate Values .txt file). However, I can't wrap my head how to implement it using your code using C. 

Do you by any chance have a C implementation for Midori128? If so, can you please provide it to me? If not, would you be willing to take a look at my code and tell me what I may be doing wrong? There are literally no repositories out there for Midori implementation :/. 

Thanks in advance.

**Comment by tomirio619** [comment]
Unfortunately I do not have a C/C++ implementation of Midori128.
If you can send me the code, I will see if I can found out what is going on.
You can find my email address on my profile page.

Kind regards,
Tom

**Comment by omarfayez95** [comment]
Thanks you! I e-mailed you. Your assistance is appreciated. I'll close this "issue" now.
